name: 'WordPress Plugin Build Zip'
description: 'Github workflow for building Wordpress plugin and theme zip'
author: 'Manuel Bachl | AppMinds.dev'

branding:
  icon: 'archive'
  color: 'blue'

inputs:
  retention-days:
    description: 'How many days to keep the zip archive'
    default: 5
  slug:
    description: 'Name of the zip archive'
    default: ${{ github.event.repository.name }}

runs:
  using: 'composite'
  steps:
    - name: Generate zip archive
      id: archive
      run: |
        echo ${{ github.event.inputs.slug }}
        cd ..
        zip -r "${{ github.event.repository.workspace }}/${{ github.event.inputs.slug }}.zip" .
      shell: bash

    - name: Unzip the archive (prevents double zip problem)
      id: unzip
      run: unzip ${{ github.event.inputs.slug }}.zip -d zipfile
      shell: bash

    - name: Upload the archive as an artifact
      id: upload-plugin-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: zipfile
        retention-days: ${{ github.event.inputs.retention-days }}
