name: 'WordPress Plugin Build Zip'
description: 'Github workflow for building Wordpress plugin and theme zip'
author: 'Manuel Bachl | AppMinds.dev'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  retention-days:
    description: 'How many days to keep the zip archive'
    default: 5
runs:
  using: 'composite'
  steps:
    # - name: Generate zip archive
    #   id: archive
    #   run: sudo ${{ github.action_path }}/build-zip.sh
    #   shell: bash

    - name: Generate zip archive
      id: archive
      run: |
        mv . ./${GITHUB_REPOSITORY#*/}
        zip -r "${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY#*/}.zip" .
      shell: bash

    - name: Unzip the archive (prevents double zip problem)
      id: unzip
      run: unzip ${{ github.event.repository.name }}.zip -d zipfile
      shell: bash

    - name: Upload the archive as an artifact
      id: upload-plugin-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: zipfile
        retention-days: ${{ inputs.retention-days }}
