name: 'WordPress Plugin Build Zip'
description: 'Github workflow for building Wordpress plugin and theme zip'
author: 'Manuel Bachl | AppMinds.dev'

branding:
  icon: 'archive'
  color: 'blue'

inputs:
  slug:
    required: false
    description: 'Name of the zip archive'
    default: ${GITHUB_REPOSITORY#*/}

runs:
  using: 'composite'
  steps:
    - name: Generate zip archive
      id: generate-zip-archive
      run: |
        cd ..
        zip -r "${GITHUB_WORKSPACE}/${{ inputs.slug }}.zip" .
      shell: bash

    - name: Unzip the archive (prevents double zip problem)
      id: unzip
      run: unzip ${{ inputs.slug }}.zip -d zipfile
      shell: bash
